// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvCGKvLNATcazWy9ATuKcIF0QaQybvz08',
    appId: '1:927355414760:web:a5c01ef7bcf570df54815d',
    messagingSenderId: '927355414760',
    projectId: 'swapu-21637',
    authDomain: 'swapu-21637.firebaseapp.com',
    storageBucket: 'swapu-21637.firebasestorage.app',
    measurementId: 'G-CXH4ST5CGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgxmwDRKImvGFuCtH3FLzy0EhDOElSM-A',
    appId: '1:927355414760:android:728fa29f0d5f1bb454815d',
    messagingSenderId: '927355414760',
    projectId: 'swapu-21637',
    storageBucket: 'swapu-21637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA5ZSCoF3SpSGZHUovXfUIG0RAmzSPuO0',
    appId: '1:927355414760:ios:2d44fe8758b3bab854815d',
    messagingSenderId: '927355414760',
    projectId: 'swapu-21637',
    storageBucket: 'swapu-21637.firebasestorage.app',
    iosBundleId: 'com.example.swapu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA5ZSCoF3SpSGZHUovXfUIG0RAmzSPuO0',
    appId: '1:927355414760:ios:2d44fe8758b3bab854815d',
    messagingSenderId: '927355414760',
    projectId: 'swapu-21637',
    storageBucket: 'swapu-21637.firebasestorage.app',
    iosBundleId: 'com.example.swapu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvCGKvLNATcazWy9ATuKcIF0QaQybvz08',
    appId: '1:927355414760:web:a2f32922ab38ac8654815d',
    messagingSenderId: '927355414760',
    projectId: 'swapu-21637',
    authDomain: 'swapu-21637.firebaseapp.com',
    storageBucket: 'swapu-21637.firebasestorage.app',
    measurementId: 'G-SRBG8P00C2',
  );

}